apiVersion: batch/v1
kind: Job
metadata:
  name: "${JOB_NAME}"
  labels:
    heritage: ${JOB_NAME}
    release: ${JOB_NAME}
    component: index
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "${JOB_NAME}"
      labels:
        heritage: ${JOB_NAME}
        release: ${JOB_NAME}
      annotations:
        iam.amazonaws.com/role: ${IAM_ROLE}
    spec:
      initContainers:
        - name: postgres-listener
          image: alpine
          command:
            [
              "sh",
              "-c",
              "for i in $(seq 1 200); do nc -z -w3 ${DB_HOST} ${DB_PORT} && exit 0 || sleep 3; done; exit 1",
            ]
      containers:
        - name: datacube-index
          image: "${IMAGE}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 768Mi
          env:
            - name: INPUT_S3_BUCKET
              value: ${INPUT_S3_BUCKET}
            - name: INPUT_FILE
              value: ${INPUT_FILE}
            - name: OUTPUT_S3_BUCKET
              value: ${OUTPUT_S3_BUCKET}
            - name: OUTPUT_PATH
              value: ${OUTPUT_PATH}
            - name: LOG_LEVEL
              value: ${LOG_LEVEL}
            - name: FILE_PREFIX
              value: ${FILE_PREFIX}
            - name: DRY_RUN
              value: ${DRY_RUN}
            - name: DB_HOSTNAME
              value: ${DB_HOST}
            - name: DB_PORT
              value: ${DB_PORT}
            - name: DB_DATABASE
              value: ${DB_DATABASE}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres-username
                  name: ${DB_DATABASE}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: ${DB_DATABASE}
            - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
              value: "30"
            - name: AWS_METADATA_SERVICE_TIMEOUT
              value: "60"
      restartPolicy: Never
